# Amazon Q pre block. Keep at the top of this file.
[[ -f "${HOME}/Library/Application Support/amazon-q/shell/zshrc.pre.zsh" ]] && builtin source "${HOME}/Library/Application Support/amazon-q/shell/zshrc.pre.zsh"
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time Oh My Zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="powerlevel10k/powerlevel10k"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
    git 
    zsh-autosuggestions 
    zsh-syntax-highlighting
    zsh-history-substring-search
    web-search 
    macos)

# Set key binding for Tab to complete-word
bindkey '^I' autosuggest-accept


source $ZSH/oh-my-zsh.sh

source $ZSH_CUSTOM/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh

# Key bindings for zsh-history-substring-search
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by Oh My Zsh libs,
# plugins, and themes. Aliases can be placed here, though Oh My Zsh
# users are encouraged to define aliases within a top-level file in
# the $ZSH_CUSTOM folder, with .zsh extension. Examples:
# - $ZSH_CUSTOM/aliases.zsh
# - $ZSH_CUSTOM/macos.zsh
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias python=python3
alias pip=pip3
alias subl="/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl"
alias cot="/Applications/CotEditor.app/Contents/MacOS/CotEditor"
alias start-yabai="yabai --start-service"
alias start-skhd="skhd --start-service"
alias stop-yabai="yabai --stop-service"
alias stop-skhd="skhd --stop-service"
alias r-yabai="yabai --restart-service"
alias r-skhd="skhd --restart-service"
alias lss="eza --group-directories-first --color=always --across --git --icons=always --no-user --no-permissions --sort=type --tree --level=2"
alias ls="eza --group-directories-first --color=always --icons=always --sort=type --time=modified"
alias cd="z"
alias openzsh="subl ~/.zshrc"
alias finder="ofd"
alias allcolors='for i in {0..255}; do print -Pn "%K{$i} %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%6)):#3}:+$'\''\n'\''}; done'

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

deactivate () {
    # Reset old environment variables
    if [ -n "${_OLD_VIRTUAL_PATH:-}" ]; then
        PATH="${_OLD_VIRTUAL_PATH:-}"
        export PATH
        unset _OLD_VIRTUAL_PATH
    fi
    if [ -n "${_OLD_VIRTUAL_PYTHONHOME:-}" ]; then
        PYTHONHOME="${_OLD_VIRTUAL_PYTHONHOME:-}"
        export PYTHONHOME
        unset _OLD_VIRTUAL_PYTHONHOME
    fi
    if [ -n "${BASH:-}" -o -n "${ZSH_VERSION:-}" ]; then
        hash -r 2> /dev/null
    fi
    if [ -n "${_OLD_VIRTUAL_PS1:-}" ]; then
        PS1="${_OLD_VIRTUAL_PS1:-}"
        export PS1
        unset _OLD_VIRTUAL_PS1
    fi
    unset VIRTUAL_ENV
    unset VIRTUAL_ENV_PROMPT
    if [ ! "${1:-}" = "nondestructive" ]; then
        unset -f deactivate
    fi
}

export PATH=$PATH:/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages

export PATH=$PATH:/Users/pranavkarra/.spicetify


# THE FUCK
eval $(thefuck --alias)
# You can use whatever you want as an alias, like for Mondays:
eval $(thefuck --alias FUCK)

eval "$(zoxide init zsh)"
export PATH="/Applications/CotEditor.app/Contents/MacOS:$PATH"
source $(brew --prefix)/share/zsh-history-substring-search/zsh-history-substring-search.zsh


echo -e '\e[31m _______                                                    \e[0m'
echo -e '\e[31m/       \                                                  \e[0m'
echo -e '\e[33m$$$$$$$  | ______   ______   _______    ______   __     __ \e[0m'
echo -e '\e[33m$$ |__$$ |/      \ /      \ /       \  /      \ /  \   /  |\e[0m'
echo -e '\e[32m$$    $$//$$$$$$  |$$$$$$  |$$$$$$$  | $$$$$$  |$$  \ /$$/ \e[0m'
echo -e '\e[32m$$$$$$$/ $$ |  $$/ /    $$ |$$ |  $$ | /    $$ | $$  /$$/  \e[0m'
echo -e '\e[36m$$ |     $$ |     /$$$$$$$ |$$ |  $$ |/$$$$$$$ |  $$ $$/   \e[0m'
echo -e '\e[36m$$ |     $$ |     $$    $$ |$$ |  $$ |$$    $$ |   $$$/    \e[0m'
echo -e '\e[34m$$/      $$/       $$$$$$$/ $$/   $$/  $$$$$$$/     $/     \e[0m'
echo -e '\e[34m __    __                                                  \e[0m'
echo -e '\e[35m/  |  /  |                                                 \e[0m'
echo -e '\e[31m$$ | /$$/   ______    ______    ______   ______            \e[0m'
echo -e '\e[33m$$ |/$$/   /      \  /      \  /      \ /      \           \e[0m'
echo -e '\e[32m$$  $$<    $$$$$$  |/$$$$$$  |/$$$$$$  |$$$$$$  |          \e[0m'
echo -e '\e[36m$$$$$  \   /    $$ |$$ |  $$/ $$ |  $$/ /    $$ |          \e[0m'
echo -e '\e[34m$$ |$$  \ /$$$$$$$ |$$ |      $$ |     /$$$$$$$ |          \e[0m'
echo -e '\e[35m$$ | $$  |$$    $$ |$$ |      $$ |     $$    $$ |          \e[0m'
echo -e '\e[31m$$/   $$/  $$$$$$$/ $$/       $$/       $$$$$$$/           \e[0m'
echo -e '\e[33m                                                           \e[0m'
echo -e '\e[32m                                                           \e[0m'
echo -e '\e[36m                                                           \e[0m'


export SSL_CERT_FILE=$(python3 -m certifi)


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Added by Windsurf
export PATH="/Users/pranavkarra/.codeium/windsurf/bin:$PATH"
alias start-media="~/scripts/start_services.sh"
alias stop-media="~/scripts/stop_services.sh"
eval "$(pyenv init --path)"
eval "$(pyenv init -)"

export PATH=~/anaconda3/bin:$PATH

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/pranavkarra/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/pranavkarra/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/pranavkarra/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/pranavkarra/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

# Amazon Q post block. Keep at the bottom of this file.
[[ -f "${HOME}/Library/Application Support/amazon-q/shell/zshrc.post.zsh" ]] && builtin source "${HOME}/Library/Application Support/amazon-q/shell/zshrc.post.zsh"

# Created by `pipx` on 2025-07-31 05:19:44
export PATH="$PATH:/Users/pranavkarra/.local/bin"
export PATH="$HOME/.local/bin:$PATH"

[[ "$TERM_PROGRAM" == "kiro" ]] && . "$(kiro --locate-shell-integration-path zsh)"

# Auto-switch GitHub account based on directory
switch_gh_user() {
    if [[ "$PWD" == "$HOME/beltic"* ]]; then
        gh auth switch -u pranav-beltic 2>/dev/null
    else
        gh auth switch -u Pranav-Karra-3301 2>/dev/null
    fi
}

precmd_functions+=(switch_gh_user)

# pnpm
export PNPM_HOME="/Users/pranavkarra/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end
